
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/app-header";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning  >
      <body className="antialiased px-4" >
         <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <SidebarProvider>
            <div className="flex flex-col md:flex-row min-h-screen w-full">
              <AppSidebar />
              <div className="flex flex-col flex-1  ">
                <Header />
                <main className="flex-1 ">{children}</main>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
